# Generated by Django 4.2.13 on 2024-05-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QE_MaturityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('manual_tests', models.IntegerField()),
                ('automated_tests', models.IntegerField()),
                ('manual_test_cost', models.FloatField()),
                ('automated_test_cost', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestAssessment',
        ),
    ]
